version: '3.1'

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: sanjeev
            MYSQL_PASSWORD: sanjeev
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

    redis:
        image: redis
        command: redis-server --appendonly yes --requirepass redis
        restart: always
        #        volumes:
        #            - redis-data:/data
        ports:
            - 6379:6379
volumes:
    mysql-data:
    #    redis-data:

