spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mydb?UseUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        testOnBorrow: true
        validationQuery: SELECT 1
        tomcat:
            max-wait: 600000
    jpa:
        show-sql: true
        database: MYSQL
        hibernate:
            #            need sequencing here
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    liquibase:
        change-log: classpath:database/liquibase.xml
        enabled: false
        drop-first: false

authentication:
    firebase:
        databaseUrl: https://solo-890ee.firebaseio.com
        configObject: solo-890ee-firebase-adminsdk-psj56-983a3a1d15.json

jwt:
    secret: SanjeevVerma
    expirationInMsec: 180000
