spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mydb?UseUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        testOnBorrow: true
        validationQuery: SELECT 1
        tomcat:
            max-wait: 600000
    jpa:
        show-sql: true
        database: MYSQL
        hibernate:
            #            need sequencing here
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    liquibase:
        change-log: classpath:database/liquibase.xml
        enabled: true
        drop-first: false

    security:
        oauth2:
            client:
                registration:
                    #                    google:
                    #                        clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
                    #                        clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
                    #                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                    #                        scope:
                    #                            - email
                    #                            - profile
                    facebook:
                        #                        clientId: 121189305185277
                        clientId: 334449210869347
                        #                        clientSecret: 42ffe5aa7379e8326387e0fe16f34132
                        clientSecret: ec2c4709499c696d61adc66826abb92b
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
                        scope:
                            - email
                            - public_profile
                #                    github:
                #                        clientId: d3e47fc2ddd966fa4352
                #                        clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
                #                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                #                        scope:
                #                            - user:email
                #                            - read:user
                provider:
                    facebook:
                        authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
                        tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
                        userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
    auth:
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
        tokenExpirationMsec: 864000000
    oauth2:
        # After successfully authenticating with the OAuth2 Provider,
        # we'll be generating an auth token for the user and sending the token to the
        # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
        # We're not using cookies because they won't work well in mobile clients.
        authorizedRedirectUris:
            - http://localhost:3000/oauth2/redirect
            - myandroidapp://oauth2/redirect
            - myiosapp://oauth2/redirect
