spring:
    datasource:
        url: jdbc:postgres://hxkgbiuxzafjde:d30a858550bd668c01ba37de813e07b6c2e19a524cbf1a64ff3b26025cf9bdcb@ec2-35-169-254-43.compute-1.amazonaws.com:5432/db4d2fk3gis56t
        username: hxkgbiuxzafjde
        password: d30a858550bd668c01ba37de813e07b6c2e19a524cbf1a64ff3b26025cf9bdcb
        testOnBorrow: true
        validationQuery: SELECT 1
        tomcat:
            max-wait: 600000
    jpa:
        show-sql: true
        database: MYSQL
        hibernate:
            #            need sequencing here
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    liquibase:
        change-log: classpath:database/liquibase.xml
        enabled: false
        drop-first: false

authentication:
    firebase:
        databaseUrl: https://solo-890ee.firebaseio.com
        configObject: solo-890ee-firebase-adminsdk-psj56-983a3a1d15.json

jwt:
    secret: SanjeevVerma
    expirationInMsec: 180000

management:
    endpoints:
        web:
            exposure:
                include: health

