spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mydb?UseUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: sanjeev
        password: sanjeev

    redis:
        host: 127.0.0.1
        password: redis
        jedis:
            pool:
                min-idle: 25
                max-active: 50
                max-idle: 25

    liquibase:
        enabled: true
        drop-first: false

jwt:
    expirationInMsec: 99999999

#logging:
#    level:
#        org.springframework: trace
#        de.sharetrip: trace
#    pattern:
#        console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#        file: "%d %p %c{1.} [%t] %m%n"
